name: "Trigger an action on all PRs with automerge set"
inputs:
  personal_access_token:
    description: "A Github Personal Access Token"
    required: true
  workflow:
    description: "The workflow to trigger (e.g. workflow.yml)"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
